### ISSUE TITLE
User Story #11

### ISSUE THREAD

**Issue by sohearn1** [seigle15/Double-Sean-with-a-side-of-Data#11]
Create a baseline GUI that will provide convenient access to all application utilities.

**Comment by sohearn1** [comment]
As a customer, I would like to have access to a clean, organized, and easy to use GUI that will provide access to all the application's core features.

**Comment by AustinStewart95** [comment]
As a customer, I would like to have access to a clean, organized, and easy to use GUI that will provide access to all the application's core features.
1.	Assumptions:
a.	Have a GUI display that displays all information corresponding to that restaurants.
b.	Have a tab layout that represents all of the corresponding features available to the customer.
2.	Tasks:
a.	Implement separate tabbed areas within the customer page for easy access to all available features.
b.	Each tabs must represent a single key feature available to the customer/Admin.
3.	Tests:
a.	Manually test the UI interface to make sure all available features for the customer and Admin are present, easy to access, and neatly organized.
4.	Definition of Done: The customer/Admin will be able to view and access all available features to them in a neatly, organized, and easy to access way.
