### ISSUE TITLE
Welcome Feature

### ISSUE THREAD

**Issue by Fishernab** [seigle15/Double-Sean-with-a-side-of-Data#15]
As a customer, When I open the program I will be greeted by a welcome feature to tell me who team members are and what the team name is

**Comment by AustinStewart95** [comment]
As a customer, When I open the program I will be greeted by a welcome feature to tell me who team members are and what the team name is
1.	Assumptions:
a.	There will be a page set up and ready to be used for set up.
2.	Tasks:
a.	Implement a new tab within the main window 
b.	Have all labels ready to be set for information
3.	Tests:
a.	Once the program is started it will then open up to the welcome page displaying the correct information.
4.	Definition of Done: The user will see the welcome page once they start the program and it will display all of the necessary and correct information about the project and the team that worked on it.
